const ADD_ITEM_TO_CART = 'Add item to cart'
const REMOVE_ITEM_FROM_CART = 'Remove item from cart'
const SET_NAVBAR_TITLE = 'SET_NAVBAR_TITLE'
const SET_SHIPPING_DETAILS = 'SET_SHIPPING_DETAILS'

export {ADD_ITEM_TO_CART, REMOVE_ITEM_FROM_CART, SET_NAVBAR_TITLE,
        SET_SHIPPING_DETAILS}