const ADD_ITEM_TO_CART = 'Add item to cart'
const REMOVE_ITEM_FROM_CART = 'Remove item from cart'
const SET_NAVBAR_TITLE = 'SET_NAVBAR_TITLE'
const SET_SHIPPING_DETAILS = 'SET_SHIPPING_DETAILS'
const SET_SINGLE_ORDER = 'SET_SINGLE_ORDER'
const SET_AUTH_DETAILS = 'SET_AUTH_DETAILS'
const SET_ONLY_LOGGED_IN_STATUS = 'SET_ONLY_LOGGED_IN_STATUS'

export {ADD_ITEM_TO_CART, REMOVE_ITEM_FROM_CART, SET_NAVBAR_TITLE,
        SET_SHIPPING_DETAILS,SET_SINGLE_ORDER, SET_AUTH_DETAILS,
        SET_ONLY_LOGGED_IN_STATUS}