const CHECKING_OUT = 'CHECKING_OUT'
const CHANGING_NAME = 'CHANGING_NAME'
const CHANGING_EMAIL = 'CHANGING_EMAIL'
const VIEWING_PROFILE = 'VIEWING_PROFILE'
const SIGNING_OUT = 'SIGNING_OUT'

export { CHECKING_OUT,CHANGING_EMAIL,CHANGING_NAME,VIEWING_PROFILE,SIGNING_OUT}